JOSS Paper content
furrer-lab/abn pull request #37
Opened 2024-03-20 16:48 UTC by j-i-l

The branch `JOSSpaper_noT` gathers all paper specific content, including `paper.md`, `paper.bib`, etc.

Content that is relevant for abn package also outside the scope of the paper, but that was added/adapted/edited during the preparation of the paper should not reside in this branch.

2024-03-26 11:19 UTC, j-i-l commented
@matteodelucchi https://github.com/furrer-lab/abn/pull/37/commits/9d4d8b9b18e8550ff5568214ec77fec40083dc2c is just a suggestion, feel free to revert or adapt :)

2024-03-26 11:48 UTC, j-i-l commented
@matteodelucchi I've also added a comment to https://github.com/orgs/furrer-lab/projects/1?pane=issue&itemId=57489555

2024-03-26 14:32 UTC, matteodelucchi commented
> @matteodelucchi I've also added a comment to https://github.com/orgs/furrer-lab/projects/1?pane=issue&itemId=57489555

thanks, reads better without the repetition.

2024-03-26 14:39 UTC, matteodelucchi approved these changes

2024-03-26 14:39 UTC, matteodelucchi commented on vignettes/paper.Rmd
we can remove this, right?

2024-04-17 15:37 UTC, matteodelucchi requested changes

2024-04-17 15:37 UTC, matteodelucchi commented on vignettes/paper.md
> +[//]: # (You switch from BN to ABN 1st paragraph, then revisit BN and again to ABN. First all BN then To ABN.)
Thanks, will improve accordingly.

2024-04-17 15:37 UTC, matteodelucchi commented on vignettes/paper.md
> +[//]: # (Next line you talk about `these limitations`. Suboptimal, ascendant not clear. Especially in the previous paragraph you only talk about `this limitation`.)
thanks!

2024-04-17 15:37 UTC, matteodelucchi commented on vignettes/paper.md
> +[//]: # (Maybe frame in line 74: more as there existed a first attempt towards mixed-effects in a Bayesian fitting context. or even a bit weaker.)
Good comment! Will change the first sentence of this section accordingly.

2024-04-17 15:37 UTC, matteodelucchi commented on vignettes/paper.md
> +[//]: # (Line 90 needed?)
We can remove it in favor of the word count. It is mentioned in more detail on the homepage anyway.

2024-04-17 15:37 UTC, matteodelucchi commented on vignettes/paper.md
> +[//]: # (Comment should be above, do you mention that this is all under `R`??)
Will make this explicit in the first sentence. Thanks!

2024-05-20 09:31 UTC, merged